### ISSUE TITLE
Class Cast Exception on rendering tree

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#116]
```
IllegalArgumentException occurred when processing request: [GET] /api/tree/folders - parameters:
includeDocumentSuperseded: false
includeModelSuperseded: true
includeDeleted: false
java.lang.ClassCastException@b3a0ff21. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@b3a0ff21
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at uk.ac.ox.softeng.maurodatamapper.core.traits.domain.PathAware$Trait$Helper.buildPath(PathAware.groovy:56)
	at uk.ac.ox.softeng.maurodatamapper.core.rest.transport.tree.TreeItem.<init>(TreeItem.groovy:66)
	at uk.ac.ox.softeng.maurodatamapper.core.rest.transport.tree.ContainerTreeItem.<init>(ContainerTreeItem.groovy:43)
	at uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService$_getAllReadableContainerTreeItems_closure20.doCall(TreeItemService.groovy:341)
	at uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.getAllReadableContainerTreeItems(TreeItemService.groovy:339)
	at uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.buildContainerTreeForModelTreeItems(TreeItemService.groovy:553)
	at uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.$tt__buildContainerTree(TreeItemService.groovy:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemController.index(TreeItemController.groovy:95)
	... 15 common frames omitted
```

**Comment by olliefreeman** [comment]
@jamesrwelch is this off the bootstrapped tree or have you done anything?

**Comment by olliefreeman** [comment]
this is the hibernateproxy/entity proxy hitting us again

**Comment by olliefreeman** [comment]
i think i have a fix, interestingly i dont get the issue using your database, but even so i know of 1 problem with the way we were solving it, so hopefully this solves this issue
