### ISSUE TITLE
Cannot add a profile, with a data type I have added, to a model

### ISSUE THREAD

**Issue by aaronforshaw** [MauroDataMapper/mdm-core#213]
**Describe the bug**
Get a ```java.lang.NullPointerException: Cannot get property 'label' on null object```when applying a profile which includes a Data Type I have added

**To Reproduce**
1. Create a new Data Model, adding the Profile Specification Data Types, and adding the Profile Specification Profile.
2. Add a Data Class to the profile
3. Add a Data Element to the Data Class, but rather than using one of the existing Data Types that was added in step 1, create a new Data Type e.g. 'Custom'
4. Save the profile
5. Navigate to a different Model (e.g. any Data Model, CodeSet etc..) and try to add the profile created above.
6. In the UI, see an error 'There was a problem getting the expected profile'. and in the logs a ```java.lang.NullPointerException: Cannot get property 'label' on null object```

**Expected behavior**
Expect to be able to add the profile, with the Data Type I added, to another model

**Screenshots**
```
java.lang.NullPointerException: Cannot get property 'label' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGetProperty(GetEffectivePogoPropertySite.java:45)
        at mdm_testing_functional_profileField__profileField_gson$_run_closure1.doCall(mdm_testing_functional_profileField__profileField_gson:15)
        at mdm_testing_functional_profileField__profileField_gson$_run_closure1.call(mdm_testing_functional_profileField__profileField_gson)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:837)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.access$000(StreamingJsonBuilder.java:501)
        at grails.plugin.json.builder.StreamingJsonBuilder.call(StreamingJsonBuilder.java:255)
        at grails.plugin.json.view.JsonViewWritableScript.json(JsonViewWritableScript.groovy:72)
        at mdm_testing_functional_profileField__profileField_gson.run(mdm_testing_functional_profileField__profileField_gson:7)
```

**Additional context**
At

https://github.com/MauroDataMapper/mdm-core/blob/3c63a679be62ddf9aa9ce0852f7baad047f08eec/mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ProfileFieldDataType.groovy#L51

the find fails to retrieve the Data Type because the label (e.g. 'Custom') does not match any of the values enumerated in ProfileFieldDataType. So a null value for dataType is propagated through to the response, which causes the exception when the view template is rendered.

**Comment by olliefreeman** [comment]
is this an issue because if someone defines an ET then it doesnt appear?? 
i would only envision allowing ETs to be custom when defining a profile as we want to limit the allowed DTs to those the UI is configured to display

**Comment by aaronforshaw** [comment]
This issue is not related to Enumeration Types. In the example, I have a Primitive Type with a label e.g. 'Custom'. The profile cannot be retrieved because 'Custom' is not one of the enum ProfileFieldDataType defined in 

https://github.com/MauroDataMapper/mdm-core/blob/3c63a679be62ddf9aa9ce0852f7baad047f08eec/mdm-plugin-profile/src/main/groovy/uk/ac/ox/softeng/maurodatamapper/profile/domain/ProfileFieldDataType.groovy#L26-L38

**Comment by olliefreeman** [comment]
@jamesrwelch how do we feel about custom profile types, i think it will break the UI as the UI depends on the types to render the profile page

**Comment by jamesrwelch** [comment]
Short term option - we either treat any custom primitive types as 'String', or we fail gracefully (maybe with a validation message on the dashboard that shows all dynamic profiles).  Longer term, we might want to allow people to specify regexes or something for their custom fields and allow them.
