### ISSUE TITLE
StaleStateException server error on retrieving data elements filtered by label

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#299]
When trying to filter the list of data elements in a class, on the label, I get the following server response:

```
2022-03-28 14:26:41,781 [080-exec-2] ERROR o.g.web.errors.GrailsExceptionResolver   : StaleStateException occurred when processing request: [GET] /api/dataModels/bb0855b5-6140-4c71-94f1-4345a1aa298a/dataClasses/dfc2bd74-98a0-4208-9b70-760fd146a4fc/dataElements - parameters:
max: 20
label: critic
Batch update returned unexpected row count from update [2]; actual row count: 0; expected: 1; statement executed: update datamodel.data_element set version=?, date_created=?, data_class_id=?, last_updated=?, path=?, min_multiplicity=?, max_multiplicity=?, breadcrumb_tree_id=?, data_type_id=?, idx=?, created_by=?, aliases_string=?, label=?, description=? where id=? and version=?. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [2]; actual row count: 0; expected: 1; statement executed: update datamodel.data_element set version=?, date_created=?, data_class_id=?, last_updated=?, path=?, min_multiplicity=?, max_multiplicity=?, breadcrumb_tree_id=?, data_type_id=?, idx=?, created_by=?, aliases_string=?, label=?, description=? where id=? and version=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [2]; actual row count: 0; expected: 1; statement executed: update datamodel.data_element set version=?, date_created=?, data_class_id=?, last_updated=?, path=?, min_multiplicity=?, max_multiplicity=?, breadcrumb_tree_id=?, data_type_id=?, idx=?, created_by=?, aliases_string=?, label=?, description=? where id=? and version=?
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:252)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:785)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:655)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:152)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.datamodel.item.DataElementController.listAllReadableResources(DataElementController.groovy:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at uk.ac.ox.softeng.maurodatamapper.core.controller.EditLoggingController.listAllResources(EditLoggingController.groovy:136)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at uk.ac.ox.softeng.maurodatamapper.datamodel.item.DataElementController.index(DataElementController.groovy:45)
	... 12 common frames omitted
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [2]; actual row count: 0; expected: 1; statement executed: update datamodel.data_element set version=?, date_created=?, data_class_id=?, last_updated=?, path=?, min_multiplicity=?, max_multiplicity=?, breadcrumb_tree_id=?, data_type_id=?, idx=?, created_by=?, aliases_string=?, label=?, description=? where id=? and version=?
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.checkRowCounts(BatchingBatch.java:151)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:126)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:106)
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:148)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:633)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1402)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:493)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3285)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2420)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:643)
	... 22 common frames omitted
```

**Comment by olliefreeman** [comment]
can you drop into debug on your code and try and work out what its trying to update inside data_element ... `update datamodel.data_element set version=?, date_created=?, data_class_id=?, last_updated=?, path=?, min_multiplicity=?, max_multip...`

or run with the sql logging and parameters turned on

The index endpoint should not be updating anything, so this is odd

**Comment by olliefreeman** [comment]
@jamesrwelch any feedback?

**Comment by olliefreeman** [comment]
figured out whats going on, 
```
 .postProcess {
                it.dataType = proxyHandler.unwrapIfProxy(it.dataType)
            }
```
in the find method is changing the DT for the DE which is then causing the seesion to want to update
