### ISSUE TITLE
MaxClauseCount is set to 1024

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#303]
```
TooManyClauses occurred when processing request: [POST] /api/folders/f594cf88-facb-4792-aa14-b528fbbe5330/search
maxClauseCount is set to 1024. Stacktrace follows:
org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
        at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:114)
        at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:127)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneBooleanPredicate.contributeQueries(LuceneBooleanPredicate.java:98)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneBooleanPredicate.doToQuery(LuceneBooleanPredicate.java:68)
        at org.hibernate.search.backend.lucene.search.predicate.impl.AbstractLuceneSearchPredicate.toQuery(AbstractLuceneSearchPredicate.java:38)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneBooleanPredicate.contributeQueries(LuceneBooleanPredicate.java:98)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneBooleanPredicate.doToQuery(LuceneBooleanPredicate.java:69)
        at org.hibernate.search.backend.lucene.search.predicate.impl.AbstractLuceneSearchPredicate.toQuery(AbstractLuceneSearchPredicate.java:38)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneSearchPredicateBuilderFactoryImpl.contribute(LuceneSearchPredicateBuilderFactoryImpl.java:50)
        at org.hibernate.search.backend.lucene.search.predicate.impl.LuceneSearchPredicateBuilderFactoryImpl.contribute(LuceneSearchPredicateBuilderFactoryImpl.java:35)
        at org.hibernate.search.engine.search.query.dsl.spi.AbstractSearchQueryOptionsStep.contribute(AbstractSearchQueryOptionsStep.java:216)
        at org.hibernate.search.engine.search.query.dsl.spi.AbstractSearchQueryOptionsStep.where(AbstractSearchQueryOptionsStep.java:70)
        at org.hibernate.search.engine.search.query.dsl.impl.DefaultSearchQuerySelectStep.where(DefaultSearchQuerySelectStep.java:92)
        at org.hibernate.search.engine.search.query.dsl.spi.AbstractDelegatingSearchQuerySelectStep.where(AbstractDelegatingSearchQuerySelectStep.java:74)
        at grails.plugins.hibernate.search.HibernateSearchApi.createFullTextQuery(HibernateSearchApi.groovy:394)
        at grails.plugins.hibernate.search.HibernateSearchApi.list(HibernateSearchApi.groovy:114)
        at uk.ac.ox.softeng.maurodatamapper.hibernate.search.HibernateSearch.paginatedList(HibernateSearch.groovy:79)
        at uk.ac.ox.softeng.maurodatamapper.hibernate.search.HibernateSearch.securedPaginatedList(HibernateSearch.groovy:43)
        at uk.ac.ox.softeng.maurodatamapper.core.model.CatalogueItem$Trait$Helper.standardHibernateSearch(CatalogueItem.groovy:108)
        at uk.ac.ox.softeng.maurodatamapper.core.search.AbstractCatalogueItemSearchService$_performStandardSearch_closure5.doCall(AbstractCatalogueItemSearchService.groovy:147)
        at uk.ac.ox.softeng.maurodatamapper.core.search.AbstractCatalogueItemSearchService.performStandardSearch(AbstractCatalogueItemSearchService.groovy:145)
        at uk.ac.ox.softeng.maurodatamapper.core.search.AbstractCatalogueItemSearchService.performSearch(AbstractCatalogueItemSearchService.groovy:126)
        at uk.ac.ox.softeng.maurodatamapper.core.search.AbstractCatalogueItemSearchService.findAllCatalogueItemsOfTypeByOwningIdsByHibernateSearch(AbstractCatalogueItemSearchService.groovy:97)
        at uk.ac.ox.softeng.maurodatamapper.core.search.SearchService.findAllByFolderIdByHibernateSearch(SearchService.groovy:55)
        at uk.ac.ox.softeng.maurodatamapper.core.container.FolderController.search(FolderController.groovy:83)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)
```
I feel like we've solved this one before...

**Comment by olliefreeman** [comment]
We definitely have

**Comment by olliefreeman** [comment]
`uk.ac.ox.softeng.maurodatamapper.hibernate.search.HibernateSearch#handleSearchException`

@jamesrwelch can you replicate this?? and work out why its not falling into the handling clause

**Comment by olliefreeman** [comment]
dont worry....i just replicated it

**Comment by olliefreeman** [comment]
its the ids and paths restricting the returned data ... i have 6K of them from 3 branches of NHSDD

**Comment by olliefreeman** [comment]
they changed the inheritance of the toomanyclauses exception from SearchException to RuntimeException
