### ISSUE TITLE
Error on main branch after deleting a previous version

### ISSUE THREAD

**Issue by pringinacio** [MauroDataMapper/mdm-core#330]
# Description

After deleting a finalized version, accessing main version start throwing exceptions.

# Steps to reproduce

1. Create a new model
2. Add a data class
3. Finalize it (version 1.0.0).
4. Create a new version of the previous model
5. Finalize it /version (1.1.0).
6. Create a new version of the previous model
7. Delete version 1.0.0
8. Try to access main version
9. An error is thrown: _Cannot get property 'id' on null object._

**Stacktrace**:

```
2022-07-06 11:43:13,240 [080-exec-2] ERROR o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /api/versionedFolders/7114f4f7-efba-40c3-9b33-32828673ff52/simpleModelVersionTree
Cannot get property 'id' on null object. Stacktrace follows:

java.lang.NullPointerException: Cannot get property 'id' on null object
	at uk.ac.ox.softeng.maurodatamapper.core.container.VersionedFolderService.$tt__findOldestAncestor(VersionedFolderService.groovy:606)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.core.container.VersionedFolderService.$tt__findOldestAncestor(VersionedFolderService.groovy:616)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.core.container.VersionedFolderService.$tt__findOldestAncestor(VersionedFolderService.groovy:616)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at uk.ac.ox.softeng.maurodatamapper.core.container.VersionedFolderController.simpleModelVersionTree(VersionedFolderController.groovy:312)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)
```

# Expected behavior

Should access main version without any error.

# Environment

Please complete the following information:
- Mauro Version 7.1.0
- mdm-core Version: 5.1.0

# Additional Context

Performing operation through Mauro UI,

# Workaround

It appears that performing the following can possibly fix the issue.

On Mauro database:

```
SELECT id FROM core.version_link WHERE multi_facet_aware_item_id = '${OFFENDING_FORDER_UUID}';

DELETE FROM core.join_versionedfolder_to_facet WHERE versionedfolder_id = '${OFFENDING_FORDER_UUID}'

DELETE FROM core.version_link WHERE id = '${id of first query}';
```

**Comment by jamesrwelch** [comment]
Hi @pringinacio Thank you very much for reporting this, and your proposed resolution.  We'll check the code and the tests, and try and get the issue resolved asap.
