### ISSUE TITLE
Cannot branch, version or fork a finalised Versioned Folder that contains child content

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#88]
**Describe the bug**

When you have a finalised Versioned Folder that contains child content (e.g. models, which are also finalised) and then try to create a new branch/version/fork of the Versioned Folder, the backend returns a `500 Internal Server Error` response. This does not happen though if doing the same for an empty finalised Versioned Folder.

**To Reproduce**

1. Create a new versioned folder called "Test Versioned Folder"
2. Under this, create a new data model called "Test Data Model"
3. Finalise "Test Versioned Folder". Note that the same model version number is applied to both "Test Versioned Folder" and "Test Data Model"
4. Now try to create a new version of "Test Versioned Folder", either:
    1. A new branch
    2. A new version, or
    3. A new fork

**Expected behavior**

A new copy of "Test Versioned Folder" should have been successfully created, with a new copy of "Test Data Model" too.

**Additional context**

The full log of the interactions from the UI can be found here:

[mdm-testing-functional.log](https://github.com/MauroDataMapper/mdm-core/files/6668631/mdm-testing-functional.log)

**Comment by olliefreeman** [comment]
odd thing is that there are tests for this with content

**Comment by olliefreeman** [comment]
This is now fixed

**Comment by olliefreeman** [comment]
not fixed

**Comment by olliefreeman** [comment]
Looking at the log file attached this is actually exactly the same issue as with #88

```stacktrace
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@76e7b921
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at uk.ac.ox.softeng.maurodatamapper.security.role.VirtualSecurableResourceGroupRoleService.buildForSecurableResource(VirtualSecurableResourceGroupRoleService.groovy:50)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService$_buildFullAccessToAllSecurableResources_closure30$_closure63$_closure64.doCall(GroupBasedSecurityPolicyManagerService.groovy:541)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService$_buildFullAccessToAllSecurableResources_closure30$_closure63.doCall(GroupBasedSecurityPolicyManagerService.groovy:540)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService$_buildFullAccessToAllSecurableResources_closure30.doCall(GroupBasedSecurityPolicyManagerService.groovy:538)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService.buildFullAccessToAllSecurableResources(GroupBasedSecurityPolicyManagerService.groovy:535)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService.buildUserSecurityPolicyManager(GroupBasedSecurityPolicyManagerService.groovy:456)
	at uk.ac.ox.softeng.maurodatamapper.security.policy.GroupBasedSecurityPolicyManagerService.$tt__buildUserSecurityPolicyManager(GroupBasedSecurityPolicyManagerService.groovy:308)
```
